/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type SpeciesPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'speciesPage';
};

export type ProductPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productPage';
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<
        | {
            href?: string;
            openInNewTab?: boolean;
            _type: 'link';
            _key: string;
          }
        | {
            species?: SpeciesPageReference;
            _type: 'speciesLink';
            _key: string;
          }
        | {
            product?: ProductPageReference;
            _type: 'productLink';
            _key: string;
          }
      >;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      variant?: 'note' | 'spec' | 'warning';
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal';
        listItem?: 'bullet';
        markDefs?: null;
        level?: number;
        _type: 'block';
        _key: string;
      }>;
      _type: 'calloutBox';
      _key: string;
    }
  | {
      image?: ImageWithAlt;
      _type: 'imageBlock';
      _key: string;
    }
>;

export type IndustryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'industry';
};

export type IndustryRef = {
  _type: 'industryRef';
  industry?: IndustryReference;
  descriptionOverride?: string;
};

export type ProductTile = {
  _type: 'productTile';
  title?: string;
  description?: string;
  href?: string;
  image?: ImageWithAlt;
};

export type SectionBlock = {
  _type: 'sectionBlock';
  eyebrow?: string;
  heading?: string;
  body?: BlockContent;
  image?: ImageWithAlt;
  cta?: CtaBlock;
};

export type RelatedSpeciesRef = {
  _type: 'relatedSpeciesRef';
  species?: SpeciesPageReference;
  descriptionOverride?: string;
};

export type ThicknessSpec = {
  _type: 'thicknessSpec';
  thickness?: string;
  widths?: Array<string>;
  dimensioning?: 'rough' | 'S3S' | 'S4S';
  note?: string;
};

export type GradeStocked = {
  _type: 'gradeStocked';
  grade?: string;
  typicalUse?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SpecRow = {
  _type: 'specRow';
  label?: string;
  value?: string;
};

export type SeoFields = {
  _type: 'seoFields';
  title?: string;
  description?: string;
  ogImage?: ImageWithAlt;
  noindex?: boolean;
  canonicalOverride?: string;
};

export type CtaBlock = {
  _type: 'ctaBlock';
  label?: string;
  href?: string;
  variant?: 'primary' | 'secondary' | 'text';
  openInNewTab?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
  caption?: string;
};

export type Article = {
  _id: string;
  _type: 'article';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroImage?: ImageWithAlt;
  publishedAt?: string;
  body?: BlockContent;
  seo?: SeoFields;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: BlockContent;
  scope?: 'delivery' | 'quote' | 'species' | 'product' | 'general';
  relatedSpecies?: SpeciesPageReference;
};

export type Industry = {
  _id: string;
  _type: 'industry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  longDescription?: BlockContent;
  icon?: string;
};

export type FaqItemReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqItem';
};

export type DeliveryPage = {
  _id: string;
  _type: 'deliveryPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  deliveryZones?: Array<{
    zone?: string;
    cities?: Array<string>;
    deliveryDays?: string;
    _key: string;
  }>;
  deliveryTiers?: Array<{
    orderMinimum?: number;
    fee?: number;
    description?: string;
    _key: string;
  }>;
  pickupBlock?: SectionBlock;
  schedulingBlock?: SectionBlock;
  faqs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  seo?: SeoFields;
};

export type QuotePage = {
  _id: string;
  _type: 'quotePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  howItWorksSteps?: Array<{
    title?: string;
    body?: BlockContent;
    _key: string;
  }>;
  quoteFormBlock?: {
    eyebrow?: string;
    heading?: string;
    bodyAboveForm?: BlockContent;
    submitLabel?: string;
    footerNote?: string;
  };
  industryOptions?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  whatToInclude?: SectionBlock;
  pickupTile?: {
    heading?: string;
    body?: BlockContent;
    cta?: CtaBlock;
  };
  deliveryTile?: {
    heading?: string;
    body?: BlockContent;
    cta?: CtaBlock;
  };
  faqs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  seo?: SeoFields;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  contactFormBlock?: {
    eyebrow?: string;
    heading?: string;
    bodyAboveForm?: BlockContent;
    submitLabel?: string;
    footerNote?: string;
  };
  industryOptions?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  quickContactPhone?: {
    heading?: string;
    phone?: string;
    hours?: string;
    bestForCopy?: BlockContent;
  };
  quickContactEmail?: {
    heading?: string;
    email?: string;
    responseTime?: string;
    bestForCopy?: BlockContent;
  };
  visitBlock?: SectionBlock;
  pickupTile?: {
    heading?: string;
    body?: BlockContent;
    cta?: CtaBlock;
  };
  deliveryTile?: {
    heading?: string;
    body?: BlockContent;
    cta?: CtaBlock;
  };
  socialBlock?: {
    eyebrow?: string;
    body?: BlockContent;
    instagramHandle?: string;
    instagramUrl?: string;
  };
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  seo?: SeoFields;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  shortVersionBlock?: SectionBlock;
  storyBlock?: SectionBlock;
  commitments?: Array<{
    title?: string;
    body?: BlockContent;
    _key: string;
  }>;
  inventoryBlock?: SectionBlock;
  millworkBlock?: SectionBlock;
  industriesBlock?: SectionBlock;
  visitBlock?: {
    eyebrow?: string;
    heading?: string;
    body?: BlockContent;
    image?: ImageWithAlt;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  seo?: SeoFields;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  subHeroBlock?: SectionBlock;
  millworkBlock?: SectionBlock;
  inventoryBlock?: SectionBlock;
  industries?: Array<
    {
      _key: string;
    } & IndustryRef
  >;
  industriesBody?: BlockContent;
  productTiles?: Array<
    {
      _key: string;
    } & ProductTile
  >;
  featuredSpecies?: Array<
    {
      _key: string;
    } & SpeciesPageReference
  >;
  featuredSpeciesCta?: CtaBlock;
  deliveryBlock?: SectionBlock;
  aboutTeaser?: SectionBlock;
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  seo?: SeoFields;
};

export type SpeciesPage = {
  _id: string;
  _type: 'speciesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  botanicalName?: string;
  category?: 'domestic-hardwood' | 'imported-hardwood' | 'softwood' | 'specialty';
  primaryKeyword?: string;
  featuredOnHome?: boolean;
  heroImage?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  hero?: {
    h1?: string;
    subhead?: string;
    leadParagraph?: BlockContent;
  };
  specsAtAGlance?: Array<
    {
      _key: string;
    } & SpecRow
  >;
  gradeIntro?: BlockContent;
  gradesStocked?: Array<
    {
      _key: string;
    } & GradeStocked
  >;
  alternativeGrades?: BlockContent;
  thicknessesStocked?: Array<
    {
      _key: string;
    } & ThicknessSpec
  >;
  figuredInventory?: BlockContent;
  whereItComesFrom?: BlockContent;
  fscNote?: BlockContent;
  grainAndAppearance?: BlockContent;
  typicalUses?: BlockContent;
  workingCharacteristics?: BlockContent;
  finishingNotes?: BlockContent;
  relatedSpecies?: Array<
    {
      _key: string;
    } & RelatedSpeciesRef
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  showMillworkCta?: boolean;
  millworkCta?: {
    heading?: string;
    body?: BlockContent;
    ctaLabel?: string;
    ctaHref?: string;
  };
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
  };
  agilityId?: string;
  notesAndDecisionsForJack?: BlockContent;
  seo?: SeoFields;
};

export type ProductPage = {
  _id: string;
  _type: 'productPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  parentProduct?: ProductPageReference;
  hero?: {
    eyebrow?: string;
    h1?: string;
    subhead?: string;
    leadParagraph?: BlockContent;
  };
  sections?: Array<
    {
      _key: string;
    } & SectionBlock
  >;
  featuredSpecies?: Array<
    {
      _key: string;
    } & SpeciesPageReference
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  finalCta?: {
    heading?: string;
    body?: BlockContent;
    primaryCta?: CtaBlock;
    secondaryCta?: CtaBlock;
  };
  agilityId?: string;
  seo?: SeoFields;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  primaryNav?: Array<{
    label?: string;
    href?: string;
    children?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  footerColumns?: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  utilityNav?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legalName?: string;
  displayName?: string;
  tagline?: string;
  phone?: string;
  email?: string;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
  };
  hours?: Array<{
    day?: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
    open?: string;
    close?: string;
    _key: string;
  }>;
  hoursNote?: string;
  social?: Array<{
    platform?: 'instagram' | 'facebook' | 'linkedin';
    url?: string;
    handle?: string;
    _key: string;
  }>;
  foundingYear?: number;
  defaultOgImage?: ImageWithAlt;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpeciesPageReference
  | ProductPageReference
  | BlockContent
  | IndustryReference
  | IndustryRef
  | ProductTile
  | SectionBlock
  | RelatedSpeciesRef
  | ThicknessSpec
  | GradeStocked
  | SpecRow
  | SeoFields
  | CtaBlock
  | SanityImageAssetReference
  | ImageWithAlt
  | Article
  | Slug
  | FaqItem
  | Industry
  | FaqItemReference
  | DeliveryPage
  | QuotePage
  | ContactPage
  | AboutPage
  | HomePage
  | SpeciesPage
  | ProductPage
  | Navigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
